#!/usr/bin/env bash

brew install duti

# Set default apps for file types
duti -s dev.zed.Zed .aliases all
duti -s dev.zed.Zed .babelrc all
duti -s dev.zed.Zed .bash_profile all
duti -s dev.zed.Zed .bash_prompt all
duti -s dev.zed.Zed .bashrc all
duti -s dev.zed.Zed .cfignore all
duti -s dev.zed.Zed .compilerc all
duti -s dev.zed.Zed .crt all
duti -s dev.zed.Zed .csr all
duti -s dev.zed.Zed .css all
duti -s dev.zed.Zed .curlrc all
duti -s dev.zed.Zed .dockerignore all
duti -s dev.zed.Zed .editorconfig all
duti -s dev.zed.Zed .ejs all
duti -s dev.zed.Zed .env all
duti -s dev.zed.Zed .eot all
duti -s dev.zed.Zed .eslintignore all
duti -s dev.zed.Zed .eslintrc all
duti -s dev.zed.Zed .example all
duti -s dev.zed.Zed .exports all
duti -s dev.zed.Zed .extra all
duti -s dev.zed.Zed .functions all
duti -s dev.zed.Zed .gdbinit all
duti -s dev.zed.Zed .git-commit-template all
duti -s dev.zed.Zed .gitattributes all
duti -s dev.zed.Zed .gitconfig all
duti -s dev.zed.Zed .gitignore all
duti -s dev.zed.Zed .graphql all
duti -s dev.zed.Zed .gvimrc all
duti -s dev.zed.Zed .hgignore all
duti -s dev.zed.Zed .hushlogin all
duti -s dev.zed.Zed .huskyrc all
duti -s dev.zed.Zed .ico all
duti -s dev.zed.Zed .idx all
duti -s dev.zed.Zed .info all
duti -s dev.zed.Zed .inputrc all
duti -s dev.zed.Zed .js all
duti -s dev.zed.Zed .jshintrc all
duti -s dev.zed.Zed .json all
duti -s dev.zed.Zed .jsx all
duti -s dev.zed.Zed .key all
duti -s dev.zed.Zed .lintstagedrc all
duti -s dev.zed.Zed .local all
duti -s dev.zed.Zed .lock all
duti -s dev.zed.Zed .log all
duti -s dev.zed.Zed .macos all
duti -s dev.zed.Zed .mailmap all
duti -s dev.zed.Zed .map all
duti -s dev.zed.Zed .md all
duti -s dev.zed.Zed .mdx all
duti -s dev.zed.Zed .nimbus all
duti -s dev.zed.Zed .node-version all
duti -s dev.zed.Zed .npmignore all
duti -s dev.zed.Zed .npmrc all
duti -s dev.zed.Zed .nvmrc all
duti -s dev.zed.Zed .nycrc all
duti -s dev.zed.Zed .opts all
duti -s dev.zed.Zed .osx all
duti -s dev.zed.Zed .otf all
duti -s dev.zed.Zed .pack all
duti -s dev.zed.Zed .pem all
duti -s dev.zed.Zed .placeholder all
duti -s dev.zed.Zed .prettierignore all
duti -s dev.zed.Zed .prettierrc all
duti -s dev.zed.Zed .sample all
duti -s dev.zed.Zed .screenrc all
duti -s dev.zed.Zed .scss all
duti -s dev.zed.Zed .sh all
duti -s dev.zed.Zed .sketch all
duti -s dev.zed.Zed .snap all
duti -s dev.zed.Zed .stylelintrc all
duti -s dev.zed.Zed .svg all
duti -s dev.zed.Zed .template all
duti -s dev.zed.Zed .terminal all
duti -s dev.zed.Zed .test all
duti -s dev.zed.Zed .toml all
duti -s dev.zed.Zed .ts all
duti -s dev.zed.Zed .tsx all
duti -s dev.zed.Zed .ttf all
duti -s dev.zed.Zed .txt all
duti -s dev.zed.Zed .vim all
duti -s dev.zed.Zed .vimrc all
duti -s dev.zed.Zed .wgetrc all
duti -s dev.zed.Zed .xml all
duti -s dev.zed.Zed .yarnrc all
duti -s dev.zed.Zed .yml all
